algo: cmame
plotting:
  algo_name: CMA-ME (${algo.emitter_type})
  
pool_size: 4

emitter_type: imp # imp, opt, rnd

annealing: 
  use_mae: false

archive:
  num_init_cvt_samples: 5000
  num_centroids: 1025

