plotting:
  algo_name: ES

pool_size: 4

archive:
  num_init_cvt_samples: 5000
  num_centroids: 1024

# Factory
factory: 
  _target_: qdax_es.factories.es.ESFactory

emitter: 
  _target_: qdax_es.core.emitters.evosax_emitter.EvosaxEmitterAll
  _partial_: true
  ns_es: false
  novelty_archive_size: 0

repertoire_init:
  _target_: qdax_es.core.containers.count_repertoire.CountMapElitesRepertoire.init
  _partial_: true