algo: mapelites

plotting:
  algo_name: MAP-Elites

archive:
  num_init_cvt_samples: 5000
  num_centroids: 1024

default_params:
  iso_sigma: 0.2
  line_sigma: 0.0
  batch_size: 64  

params:
  iso_sigma: ${oc.select:algo.env_params.${task.env_name}.iso_sigma, ${algo.default_params.iso_sigma}}
  line_sigma: ${oc.select:algo.env_params.${task.env_name}.line_sigma, ${algo.default_params.line_sigma}}
  batch_size: ${oc.select:algo.env_params.${task.env_name}.batch_size, ${algo.default_params.batch_size}}


env_params:
  halfcheetah_uni: 
    iso_sigma: 0.005
    line_sigma: 0.05
    batch_size: 1024
  walker2d_uni:
    iso_sigma: 0.005
    line_sigma: 0.05
    batch_size: 1024