defaults:
  - override launcher: joblib
  - _self_

job:
  chdir: True
run:
  dir: ./output/${now:%Y-%m-%d_%H%M%S_%f}

sweep:
  dir: ./output/${now:%Y-%m-%d_%H%M%S_%f}
  subdir: ${hydra.job.num}

sweeper:
  params:
    algo.params.alpha: 0.1, 0.3, 0.5, 0.7, 0.9
    seed: range(2)
    task: kh_standard
    #, kh_snake, kh_standard
    # task: halfcheetah, walker_2d
    algo: jedi, dy_jedi

launcher:
  n_jobs: 5