defaults:
  - override launcher: joblib
  - _self_

launcher:
  n_jobs: 10


job:
  chdir: True
run:
  dir: ./workdir/output
sweep:
  dir: ./workdir/output
  subdir: ${hydra.job.num}

# sweeper:
#   params:
#     seed: "\$RANDOM"