plotting:
  algo_name: CMA-ME (${algo.emitter.emitter_type})
  
pool_size: 4

archive:
  num_init_cvt_samples: 5000
  num_centroids: 1024

# Factory
factory: 
  _target_: qdax_es.factories.cmame.CMAMEFactory

emitter: 
  _target_: qdax_es.core.emitters.cma_me_emitter.CMAMEEmitter
  _partial_: true
  emitter_type: imp # imp, opt, rnd

repertoire_init:
  _target_: qdax_es.core.containers.count_repertoire.CountMapElitesRepertoire.init
  _partial_: true