defaults:
  - jedi # Inherit all settings from jedi.yaml
  - override target: gp
  - override restarter: cma
  - _self_ # Allow overriding inherited values

alpha_defaults:
  kheperax:
    default: decay
    kheperax_pointmaze: 0.3
    kheperax_snake: 0.3
    kheperax_standard: 0.7
  brax:
    default: decay
    halfcheetah_uni: 0.3
    walker2d_uni: 0.3
    antmaze: 0.3
  optim:
    default: 0.3
  bbob:
    default: 0.3
