defaults:
  - default_qd # Inherit all settings from default_qd
  - es_params # Inherit ES parameters
  - restarter: cma
  - _self_ # Allow overriding inherited values

plotting:
  algo_name: ${algo.params.es_type}

# Factory
factory: 
  _target_: qdax_es.factories.es.ESFactory

repertoire_init:
  _target_: qdax_es.core.containers.count_repertoire.CountMapElitesRepertoire.init
  _partial_: true

emitter: 
  _target_: qdax_es.core.emitters.evosax_emitter.EvosaxEmitterAll
  _partial_: true
  population_size: ${algo.params.population_size}
  es_type: ${algo.params.es_type}
  std_init: ${algo.params.std_init}
  ns_es: false
  novelty_archive_size: 0
  restarter: ${algo.restarter.builder}

initial_batch: 1