defaults:
  - es # Inherit all settings from es.yaml
  - _self_ # Allow overriding inherited values

plotting:
  algo_name: NS-ES

emitter: 
  _target_: qdax_es.core.emitters.evosax_emitter.EvosaxEmitterAll
  _partial_: true
  ns_es: true
  novelty_archive_size: 1024

