defaults:
  - kh_standard # Inherit all settings from kheperax_base.yaml
  - _self_ # Allow overriding inherited values

env_name: kheperax_snake


total_evaluations: 1e6

jedi:
  alpha: 0.3
  gens: 100

plotting:
  task_name: Kheperax Snake
  fitness_bounds: [-400, -100]
  max_eval_cell: 5.5
