# Weighted GP JEDi
defaults:
  - gp # Inherit all settings from gp.yaml
  - _self_ # Allow overriding inherited values

name: WGP ${algo.target.tournament_size}

target_selector:
  _target_: qdax_es.utils.target_selection.GPSelector
  # _partial_: true
  gp_steps: ${algo.target.steps}
  pareto_depth: ${algo.target.pareto_depth}
  n_points: 1
  tournament_size: ${oc.select:algo.target.tournament_size, ${algo.archive.num_centroids}}
  gp: 
    _target_: qdax_es.utils.gaussian_processes.weighted_gp.WeightedGaussianProcess
    kernel_fn: 
      _target_: qdax_es.utils.gaussian_processes.base_gp.rbf_kernel
      _partial_: true