defaults:
  - algo: me
  - task: optim/arm
  - hydra: local
  - _self_

hydra:
  searchpath: 
    - pkg://qdax_bench.configs

num_loops: 100
seed: 42
plots_dir: plots

corrected_metrics: 
  use: false
  evals: 128

wandb:
  project: JEDiTELO
  entity: p-templier-imperial-college-london
  use: False
  tag: null

csv:
  use: True
  subsample: 10

plot: True